"""Seed data used to populate a fresh Bristol Community Events database."""

DEFAULT_REVIEWS = [
    {
        "seed_key": "demo-john-smith",
        "author_name": "John Smith",
        "author_initials": "JS",
        "rating": 5,
        "content": "I checked what was on around the harbourside and found a couple of events I'd actually go to.",
        "status": "Approved",
    },
    {
        "seed_key": "demo-emily-carter",
        "author_name": "Emily Carter",
        "author_initials": "EC",
        "rating": 4,
        "content": "The filters make it easy to narrow things down by date and price without jumping between pages.",
        "status": "Approved",
    },
    {
        "seed_key": "demo-david-brown",
        "author_name": "David Brown",
        "author_initials": "DB",
        "rating": 5,
        "content": "Booking was straightforward, and the receipt was ready straight away.",
        "status": "Approved",
    },
    {
        "seed_key": "demo-aisha-rahman",
        "author_name": "Aisha Rahman",
        "author_initials": "AR",
        "rating": 4,
        "content": "I like seeing the venue, location, and capacity together before I decide.",
        "status": "Approved",
    },
    {
        "seed_key": "demo-sofia-patel",
        "author_name": "Sofia Patel",
        "author_initials": "SP",
        "rating": 5,
        "content": "The student discount is useful, especially for pricier events.",
        "status": "Approved",
    },
    {
        "seed_key": "demo-daniel-green",
        "author_name": "Daniel Green",
        "author_initials": "DG",
        "rating": 4,
        "content": "It feels like a practical local events site rather than a generic ticket page.",
        "status": "Approved",
    },
]

DEFAULT_VENUES = [
    {
        "venue_name": "Bristol City Centre Hall",
        "address": "Broad Street",
        "city": "Bristol",
        "capacity": 500,
    },
    {
        "venue_name": "Harbourside Gallery",
        "address": "Dock Road",
        "city": "Bristol",
        "capacity": 300,
    },
    {
        "venue_name": "Ashton Court Estate",
        "address": "Ashton Court",
        "city": "Bristol",
        "capacity": 400,
    },
    {
        "venue_name": "Bristol Indoor Arena",
        "address": "Arena Road",
        "city": "Bristol",
        "capacity": 500,
    },
    {
        "venue_name": "Harbourside Art Space",
        "address": "Dock Street",
        "city": "Bristol",
        "capacity": 300,
    },
    {
        "venue_name": "UWE Exhibition Hall",
        "address": "Frenchay Campus",
        "city": "Bristol",
        "capacity": 400,
    },
]

DEFAULT_CATEGORIES = [
    {"category_name": "Arts"},
    {"category_name": "Family"},
    {"category_name": "Festival"},
    {"category_name": "Food & Drink"},
    {"category_name": "Music"},
    {"category_name": "Outdoor"},
]

DEFAULT_EVENTS = [
    {
        "seed_key": "demo-bristol-makers-market",
        "event_name": "Bristol Makers Market",
        "description": "A two-day market for local makers, illustrators, and small creative businesses.",
        "event_date": "2026-04-10",
        "event_end_date": "2026-04-11",
        "location": "Cabot Circus, Bristol",
        "conditions": "Book 1 to 2 days. Ideal for trying the multi-day booking flow.",
        "price": "12.00",
        "venue_name": "Bristol City Centre Hall",
        "category_name": "Arts",
        "event_capacity": 500,
        "image_url": "/static/images/events/event-card-8.jpg",
    },
    {
        "seed_key": "demo-harbourside-lanterns",
        "event_name": "Harbourside Lantern Walk",
        "description": "An evening walk along the harbour with light installations and live performers.",
        "event_date": "2026-04-20",
        "event_end_date": "2026-04-21",
        "location": "Harbourside, Bristol",
        "conditions": "Book 1 or 2 days. Great for checking the 5% advance discount band.",
        "price": "18.00",
        "venue_name": "Harbourside Art Space",
        "category_name": "Outdoor",
        "event_capacity": 300,
        "image_url": "/static/images/events/event-card-9.jpg",
    },
    {
        "seed_key": "demo-family-science-weekend",
        "event_name": "Family Science Weekend",
        "description": "Hands-on science demos, workshops, and activities for families and students.",
        "event_date": "2026-04-30",
        "event_end_date": "2026-05-02",
        "location": "Frenchay Campus, Bristol",
        "conditions": "Book 1 to 3 days. This event is useful for testing the 10% advance discount band.",
        "price": "36.00",
        "venue_name": "UWE Exhibition Hall",
        "category_name": "Family",
        "event_capacity": 400,
        "image_url": "/static/images/events/event-card-10.jpg",
    },
    {
        "seed_key": "demo-harbourside-sessions",
        "event_name": "Harbourside Summer Sessions",
        "description": "A weekend programme of live music, food stalls, and open-air performances.",
        "event_date": "2026-05-15",
        "event_end_date": "2026-05-17",
        "location": "Harbourside, Bristol",
        "conditions": "Book 1 to 3 days. This event sits in the 15% advance discount band.",
        "price": "45.00",
        "venue_name": "Harbourside Gallery",
        "category_name": "Music",
        "event_capacity": 300,
        "image_url": "/static/images/events/event-card-11.jpg",
    },
    {
        "seed_key": "demo-bristol-food-trail",
        "event_name": "Bristol Food & Craft Trail",
        "description": "A three-day trail of tastings, demos, and handmade goods across the city centre.",
        "event_date": "2026-05-30",
        "event_end_date": "2026-06-01",
        "location": "City Centre, Bristol",
        "conditions": "Book 1 to 3 days. This event is designed to test the 20% advance discount band.",
        "price": "60.00",
        "venue_name": "Bristol City Centre Hall",
        "category_name": "Food & Drink",
        "event_capacity": 500,
        "image_url": "/static/images/events/event-card-12.jpg",
    },
    {
        "seed_key": "demo-bristol-balloon-fiesta",
        "event_name": "Bristol Balloon Fiesta",
        "description": "A week-long celebration with balloons, family activities, and evening displays.",
        "event_date": "2026-08-01",
        "event_end_date": "2026-08-07",
        "location": "Ashton Court, Bristol",
        "conditions": "Book 1 to 7 days. Each booked day is charged as part of the total event price.",
        "price": "70.00",
        "venue_name": "Ashton Court Estate",
        "category_name": "Festival",
        "event_capacity": 400,
        "image_url": "/static/images/events/event-card-13.jpg",
    },
]

DEFAULT_EVENT_IMAGES = [
    "/static/images/events/event-card-1.jpg",
    "/static/images/events/event-card-2.jpg",
    "/static/images/events/event-card-3.jpg",
    "/static/images/events/event-card-4.jpg",
    "/static/images/events/event-card-5.jpg",
    "/static/images/events/event-card-6.jpg",
    "/static/images/events/event-card-7.jpg",
]
