"""Seed data used to populate a fresh Bristol Community Events database."""

DEFAULT_REVIEWS = [
    {
        "seed_key": "demo-john-smith",
        "author_name": "John Smith",
        "author_initials": "JS",
        "rating": 5,
        "content": "I checked what was on around the harbourside and found a couple of events I'd actually go to.",
        "status": "Approved",
    },
    {
        "seed_key": "demo-emily-carter",
        "author_name": "Emily Carter",
        "author_initials": "EC",
        "rating": 4,
        "content": "The filters make it easy to narrow things down by date and price without jumping between pages.",
        "status": "Approved",
    },
    {
        "seed_key": "demo-david-brown",
        "author_name": "David Brown",
        "author_initials": "DB",
        "rating": 5,
        "content": "Booking was straightforward, and the receipt was ready straight away.",
        "status": "Approved",
    },
    {
        "seed_key": "demo-aisha-rahman",
        "author_name": "Aisha Rahman",
        "author_initials": "AR",
        "rating": 4,
        "content": "I like seeing the venue, location, and capacity together before I decide.",
        "status": "Approved",
    },
    {
        "seed_key": "demo-sofia-patel",
        "author_name": "Sofia Patel",
        "author_initials": "SP",
        "rating": 5,
        "content": "The student discount is useful, especially for pricier events.",
        "status": "Approved",
    },
    {
        "seed_key": "demo-daniel-green",
        "author_name": "Daniel Green",
        "author_initials": "DG",
        "rating": 4,
        "content": "It feels like a practical local events site rather than a generic ticket page.",
        "status": "Approved",
    },
]

DEFAULT_VENUES = [
    {
        "venue_name": "Bristol City Centre Hall",
        "address": "Broad Street, Bristol BS1 2EA",
        "city": "Bristol",
        "capacity": 500,
        "suitable_for": "Conferences, Exhibitions, Community Gatherings",
        "image_url": "images/venue/Bristol City Centre Hall.jpg",
    },
    {
        "venue_name": "Harbourside Art Space",
        "address": "Dock Street, Bristol BS1 5AQ",
        "city": "Bristol",
        "capacity": 300,
        "suitable_for": "Exhibitions, Workshops, Music",
        "image_url": "images/venue/Harbourside Art Space.jpg",
    },
    {
        "venue_name": "Ashton Court Estate",
        "address": "Ashton Court Estate, Long Ashton, Bristol BS41 9JN",
        "city": "Bristol",
        "capacity": 400,
        "suitable_for": "Outdoor Events, Festivals, Exhibitions",
        "image_url": "images/venue/Ashton Court Estate.jpg",
    },
    {
        "venue_name": "Bristol Indoor Arena",
        "address": "Arena Road, Bristol BS1 5TT",
        "city": "Bristol",
        "capacity": 500,
        "suitable_for": "Sports, Concerts, Exhibitions",
        "image_url": "images/venue/Bristol Indoor Arena.jpg",
    },
    {
        "venue_name": "Ashton Gate Stadium",
        "address": "Ashton Gate Stadium, Ashton Road, Bristol BS3 2EJ",
        "city": "Bristol",
        "capacity": 150,
        "suitable_for": "Musical, Sports, Exhibitions",
        "image_url": "images/venue/Ashton Gate Stadium.jpg",
    },
    {
        "venue_name": "Arnolfini",
        "address": "16 Narrow Quay, Bristol BS1 4QA",
        "city": "Bristol",
        "capacity": 100,
        "suitable_for": "Exhibitions, Workshops",
        "image_url": "images/venue/Arnolfini.jpg",
    },
    {
        "venue_name": "The Bristol Hippodrome",
        "address": "St Augustine's Parade, Bristol BS1 4UZ",
        "city": "Bristol",
        "capacity": 120,
        "suitable_for": "Theatre, Musical",
        "image_url": "images/venue/The Bristol Hippodrome.jpg",
    },
    {
        "venue_name": "Bristol Old Vic",
        "address": "King Street, Bristol BS1 4ED",
        "city": "Bristol",
        "capacity": 110,
        "suitable_for": "Theatre",
        "image_url": "images/venue/Bristol Old Vic.jpg",
    },
    {
        "venue_name": "Bristol Central Library",
        "address": "Deanery Road, City Centre, Bristol BS1 5TL",
        "city": "Bristol",
        "capacity": 50,
        "suitable_for": "Library Exhibitions",
        "image_url": "images/venue/Bristol Central Library.jpg",
    },
    {
        "venue_name": "Royal West of England Academy",
        "address": "Queens Road, Clifton, Bristol BS8 1PX",
        "city": "Bristol",
        "capacity": 100,
        "suitable_for": "Exhibitions",
        "image_url": "images/venue/Royal West of England Academy.jpg",
    },
    {
        "venue_name": "UWE Exhibition Centre",
        "address": "North Entrance, Frenchay Campus, Filton Road, Bristol BS34 8QZ",
        "city": "Bristol",
        "capacity": 300,
        "suitable_for": "Wedding, Workshops, Conference, Exhibitions",
        "image_url": "images/venue/UWE Exhibition Centre.jpg",
    },
    {
        "venue_name": "Creative Space A",
        "address": "28 King Street, Bristol BS1 4EF",
        "city": "Bristol",
        "capacity": 30,
        "suitable_for": "Workshops",
        "image_url": "images/venue/Creative Space A.jpg",
    },
    {
        "venue_name": "Creative Space B",
        "address": "12 Temple Gate, Bristol BS1 6ED",
        "city": "Bristol",
        "capacity": 50,
        "suitable_for": "Workshops, Courses",
        "image_url": "images/venue/Creative Space B.jpg",
    },
    {
        "venue_name": "Community Centre A",
        "address": "101 Church Road, Bristol BS5 8AF",
        "city": "Bristol",
        "capacity": 60,
        "suitable_for": "Private events (e.g., birthday parties, religious events)",
        "image_url": "images/venue/Community Centre A.jpg",
    },
]

DEFAULT_CATEGORIES = [
    {"category_name": "Arts"},
    {"category_name": "Family"},
    {"category_name": "Festival"},
    {"category_name": "Food & Drink"},
    {"category_name": "Music"},
    {"category_name": "Outdoor"},
]

DEFAULT_EVENTS = [
    {
        "seed_key": "demo-bristol-makers-market",
        "event_name": "Bristol Makers Market",
        "description": "A two-day market for local makers, illustrators, and small creative businesses.",
        "event_date": "2026-04-10",
        "event_end_date": "2026-04-11",
        "event_time": "10:00 - 16:00",
        "location": "Cabot Circus, Bristol",
        "conditions": "Book 1 to 2 days. Ideal for trying the multi-day booking flow.",
        "price": "12.00",
        "venue_name": "Bristol City Centre Hall",
        "category_name": "Arts",
        "event_capacity": 500,
        "image_url": "/static/images/event/event-card-24.jpg",
    },
    {
        "seed_key": "demo-family-science-weekend",
        "event_name": "Family Science Weekend",
        "description": "Hands-on science demos, workshops, and activities for families and students.",
        "event_date": "2026-04-30",
        "event_end_date": "2026-05-02",
        "event_time": "10:00 - 17:00",
        "location": "Frenchay Campus, Bristol",
        "conditions": "Book 1 to 3 days. This event is useful for testing the 10% advance discount band.",
        "price": "36.00",
        "venue_name": "UWE Exhibition Centre",
        "category_name": "Family",
        "event_capacity": 400,
        "image_url": "/static/images/event/event-card-44.jpg",
    },
    {
        "seed_key": "demo-bristol-food-trail",
        "event_name": "Bristol Food & Craft Trail",
        "description": "A three-day trail of tastings, demos, and handmade goods across the city centre.",
        "event_date": "2026-05-30",
        "event_end_date": "2026-06-01",
        "event_time": "11:00 - 18:00",
        "location": "City Centre, Bristol",
        "conditions": "Book 1 to 3 days. This event is designed to test the 20% advance discount band.",
        "price": "60.00",
        "venue_name": "Bristol City Centre Hall",
        "category_name": "Food & Drink",
        "event_capacity": 500,
        "image_url": "/static/images/event/event-card-47.jpg",
    },
    {
        "seed_key": "demo-bristol-balloon-fiesta",
        "event_name": "Bristol Balloon Fiesta",
        "description": "A week-long celebration with balloons, family activities, and evening displays.",
        "event_date": "2026-08-01",
        "event_end_date": "2026-08-07",
        "event_time": "10:00 - 22:00",
        "location": "Ashton Court, Bristol",
        "conditions": "Book 1 to 7 days. Each booked day is charged as part of the total event price.",
        "price": "70.00",
        "venue_name": "Ashton Court Estate",
        "category_name": "Festival",
        "event_capacity": 400,
        "image_url": "/static/images/event/event-card-36.jpg",
    },
]

DEFAULT_EVENT_IMAGES = [
    "/static/images/event/event-card-1.jpg",
    "/static/images/event/event-card-2.jpg",
    "/static/images/event/event-card-3.jpg",
    "/static/images/event/event-card-4.jpg",
    "/static/images/event/event-card-5.jpg",
    "/static/images/event/event-card-6.jpg",
    "/static/images/event/event-card-7.jpg",
]
